### ISSUE TITLE
Feedback Cadastrar histórias no gitHub

### ISSUE THREAD

**Issue by lsca** [IF977/CHAMA_O_SAMU#11]
E ai pessoal, tudo certinho??
Fiquei de corrigir a nota de vocês a respeito de "Cadastrar histórias no gitHub". Só que, há apenas 1 issue na milestone da iteração 2. Confere? só foi implementada uma issue?

**Comment by marcustib** [comment]
Sim lucas, só foi implementada uma issue.

**Comment by lsca** [comment]
Pronto, como nota na iteração 2 vocês ficaram com 10. Porém, houve uma penalização de 3 pontos a vocês pelo fato de o grupo ter 3 pessoas e apenas 1 issue implementada nessa iteração(nota 7). Duvidas falar comigo no slack. Peço que fechem a issue.

**Comment by marcustib** [comment]
Okey, obrigado pelo feedback
